print("Welcome to my first day of coding!")
print("I have written the following program to one of my favorite Mad Libs titled \"Bears\"")
print("Type the requested word and then hit enter. Once completed your story will be generated.")
print("Enjoy!")
print("")

adjective_0 = input("Enter an adjective: ")
noun_0 = input("Enter a noun: ")
plural_noun_0 = input("Enter a plural noun: ")
adjective_1 = input("Enter an adjective: ")
adjective_2 = input("Enter an adjective: ")
verb_ending_in_ing_0 = input("Enter a verb ending in \"ing\": ")
verb_ending_in_ing_1 = input("Enter a verb ending in \"ing\": ")
adjective_3 = input("Enter an adjective: ")
adjective_4 = input("Enter an adjective: ")
noun_1 = input("Enter a noun: ")
type_of_food_0 = input("Enter a type of food (plural): ")
part_of_the_body_0 = input("Enter a part of the body (plural): ")
adjective_5 = input("Enter an adjective: ")
vehicle_0 = input("Enter a vehicle: ")
type_of_food_1 = input("Enter a type of food (plural): ")
type_of_food_2 = input("Enter a type of food (plural): ")
something_alive_0 = input("Enter something alive (plural): ")
something_alive_1 = input("Enter something alive (plural): ")
adverb_0 = input("Enter an adverb: ")
noun_2 = input("Enter a noun: ")

print("")

print("If you go to some " + adjective_0 + " place like Yellowstone National " + noun_0 + ",")
print("You must know how to deal with wild animals such as bears and wolves and " + plural_noun_0 + ".")
print("The most important of these is the bear. There are three kinds of bears at Yellowstone:")
print("the grizzly bear, the " + adjective_1 + " bear, and the " + adjective_2 + " bear.")
print("Bears spend most of their time " + verb_ending_in_ing_0 + " or " + verb_ending_in_ing_1 + ".")
print("They look very " + adjective_3 + ", but if you make them " + adjective_4 + ", they might bite your " + noun_1 + ".")
print("Bears will come up to your car and beg for " + type_of_food_0 + ".")
print("They will stand on their hind legs and clap their " + part_of_the_body_0 + " together and pretend to be " + adjective_5 + ".")
print("But do not get out of your " + vehicle_0 + " or offer the bears " + type_of_food_1 + " or " + type_of_food_2 + ".")
print("This same advice applies to other wild creatures such as " + something_alive_0 + " and " + something_alive_1 + ".")
print("Remember all these rules and you will spend your vacation " + adverb_0 + " and not get eaten by a/an " + noun_2 + ".")